# site settings

title: Alireza Habibzadeh
description: Computer Engineering and Physics student
taglong: Computer Engineering and Physics student
taglong2: Sharif University of Technology
tagshort: Student at SUT
url: https://alirezahabib.me
baseurl: ""
permalink: pretty
repo: https://github.com/alirezahabib/alirezahabib.github.io

# author settings

author:
  name: Alireza Habibzadeh
  email: alirezahabib80@gmail.com
photo: /assets/jpg/photo.webp

# social media links

social:
  github: alirezahabib
  linkedin: alirezahabibzadeh
  orcid: 0009-0004-8747-3843
  # twitter: username
  # instagram: username
  # stackoverflow: 0000000/username
  # facebook: username

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
